tbl_daftar_km
id_daftar_km
kode_daftar_km
nomor_kontrak
nama_kontrak
tanggal_kontrak
tahun_anggaran
add_terupdate
nilai_addendum_terupdate


tbl_detail_daftar_km
id_detail_daftar_km
kode_detail_daftar_km
kode_daftar_km
level
nama_program
keterangan_kontrak
nilai_proyek

tbl_detail_rencana_km
id_detail_rencana_km
kode_detail_rencana_km
kode_detail_daftar_km
bulan
nilai_rencana
sts_bulan

tbl_detail_realisasi_km
id_detail_realisasi_km
kode_detail_rencana_km
bulan
nilai_realiasasi
sts_bulan